gcon/gcon/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('social_django.urls', namespace='social')),
    url('', include('main.urls', namespace='main')),
]

gcon/main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^repos/$', views.repos, name='repos'),
    # Todo: add regexp
    url(r'^hook/(?P<repo_name>.+)/$', views.create_hook, name='hook'),
    url(r'^handle/$', views.handle_hook, name='handle'),
    url(r'^logout/$', views.logout_user, name='logout')
]

gcon/main/models.py
from django.db import models

# Create your models here.

gcon/main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from django.http.response import HttpResponse
from social_django.models import UserSocialAuth
from github import Github
from main import sensitive_data
from json import loads


def get_github(user):
    # Todo: may be not found
    user_social_auth = UserSocialAuth.objects.get(user=user)
    access_token = user_social_auth.extra_data['access_token']
    return Github(user_social_auth.user.username, access_token)


def get_auth_github(username):
    user = User.objects.get(username=username)
    return get_github(user)


def index(request):
    return render(request, 'index.html')


@login_required
def repos(request):
    g = get_github(request.user)
    repos = g.get_user().get_repos()

    repo_data = []
    for repo in repos:
        repo_data.append({'name': repo.name, 'full_name': repo.full_name})

    return render(request, 'repos.html', {'repos': repo_data})


@login_required
@require_http_methods(['POST'])
def create_hook(request, repo_name):
    
    g = get_github(request.user)
    user = g.get_user()
    repo = user.get_repo(repo_name)

    print(repo)

    config = {
        'url': sensitive_data.WEBHOOK_URL,
        'content_type': 'json',
    }
    try:
        hook = repo.create_hook('web', config, ['pull_request'], True)
        print(hook)
    except:
        # Do nothing
        pass

    return redirect('/repos/')


@csrf_exempt
@require_http_methods(['POST'])
def handle_hook(request):

    print(request.body)

    body = loads(request.body.decode())

    if not 'action' in body or body['action'] != 'opened':
        return HttpResponse()

    print('\nOPENED\n')

    repo_name = body['repository']['name']
    owner = body['repository']['owner']['login']

    print(owner)

    g = get_auth_github(owner)
    user = g.get_user()
    repo = user.get_repo(repo_name)

    print(repo)

    pull = repo.get_pulls()[0]

    print(pull)

    file = pull.get_files()[0]

    print(file)

    print(file.filename, file.contents_url, file.blob_url)

    commit = pull.get_commits()[0]

    print(commit)

    pull.create_comment('service', commit, 'file', 1)

    return HttpResponse()


@login_required
def logout_user(request):
    logout(request)
    return redirect('/')

gcon/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>{% block title %}{% endblock %}</title>

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    </head>
    <body>

        <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="{% url 'main:index' %}">gcon</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {% block home %}{% endblock %}">
                        <a class="nav-link" href="{% url 'main:index' %}">Home</a>
                    </li>

                    {% if user.is_authenticated %}
                        <li class="nav-item {% block repos %}{% endblock %}">
                            <a class="nav-link" href="{% url 'main:repos' %}">Repos</a>
                        </li>
                    {% endif %}

                </ul>

                {% if not user.is_authenticated %}
                    <a href="{% url 'social:begin' 'github' %}" class="btn btn-outline-secondary my-2 my-sm-0">Sign In With GitHub</a>
                {% else %}
                    <a href="{% url 'main:logout' %}" class="btn btn-outline-secondary my-2 my-sm-0">Sign Out</a>
                {% endif %}

            </div>
        </nav>

        <div class="container">

            {% block content %}{% endblock %}

            <hr>

            <footer>
                <p>&copy; gcon 2017</p>
            </footer>
        </div>

        <!-- jQuery first, then Tether, then Bootstrap JS. -->
        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    </body>
</html>

gcon/main/templates/handle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <h1>HANDLE</h1>

</head>
<body>

</body>
</html>

gcon/main/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Main page
{% endblock %}

{% block home %}active{% endblock %}

{% block content %}

    <br>

    <div class="jumbotron">
        <h1 class="display-3">
            Main page
        </h1>
    </div>

{% endblock %}

gcon/main/templates/repos.html
{% extends 'base.html' %}

{% block title %}
    Repos
{% endblock %}

{% block repos %}active{% endblock %}

{% block content %}

    <br>

    <h4>
        Repos
    </h4>

    <ul>
        {% for repo in repos %}
            <li>
                <form method="post" action="{% url 'main:hook' repo_name=repo.name %}">
                    {% csrf_token %}
                    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Подключить</button>
                    <a href="#">{{ repo.full_name }}</a>
                </form>
                <br>
            </li>
        {% endfor %}
    </ul>

{% endblock %}